### ISSUE TITLE
App crashes on start on iOS 7

### ISSUE THREAD

**Issue by girst** [davidjb/pass-ios#12]
Hi, its me again. 
I installed the app, copied my .password-store and imported and trusted my gpg-key. 

When I click on the App-icon to launch it, it crashes immediately. 
I tried to launch the executable from the terminal-app, which gave me this:
```
    $ ./pass
    dyld: Symbol not found: ___NSDictionary0__
      Referenced from: ....../pass.app/./pass
      Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
      in ...../pass.app/./pass
    Trace /BPT trap: 5
    $echo $?
    133
```

**Comment by davidjb** [comment]
What's your iOS version and hardware model? See if there's any key
differences between your device and mine and go from there.

**Comment by girst** [comment]
iOS 7.2.1 on the iPad Air 1

(thanks for putting up with me :S)

**Comment by davidjb** [comment]
Right, that's why.  The app is built for the iOS 9 SDK and iOS9, and
currently requires iOS 8 due to the cleanup and removal of deprecated
classes (UIAlertView to UIAlertController) and use of the secure enclave in
Valet.

I'm open to the possibility of a PR that reinstates iOS 7 support, however
I don't have the requirement for it.

**Comment by davidjb** [comment]
I'll close this for now; reference it in a pull request if adding iOS7 support.
