### ISSUE TITLE
Is this obsolete?

### ISSUE THREAD

**Issue by therockmandolinist** [davidjb/pass-ios#16]
Is this app still usable? If so, the instructions probably need updating. Of not, perhaps the README should reflect that, and - is there currently any working way to integrate pass with IOS?

**Comment by davidjb** [comment]
I'm using the latest codebase but I haven't tested it on iOS 10.  There's discussion about other options at https://github.com/davidjb/pass-ios/issues/8, though I can't comment on the suggestions there.  My plan is to, if possible, revamp this into a cross-platform solution.  Very much a WIP over at https://github.com/davidjb/passport.  

PR etc are welcome here if you're able to contribute; otherwise comment away over at #8.
